<Project Sdk="Aspire.AppHost.Sdk/13.6.0">

  <ItemGroup>
    <ProjectReference Include="..\Microshop.CatalogApi\Microshop.CatalogApi.csproj" />
    <ProjectReference Include="..\Microshop.BasketApi\Microshop.BasketApi.csproj" />
    <ProjectReference Include="..\Microshop.IdentityApi\Microshop.IdentityApi.csproj" />
    <ProjectReference Include="..\Microshop.OrderingApi\Microshop.OrderingApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.0.0" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.0.0" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="9.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>7ec7d1f8-98d7-46a2-9178-728a04f1a24b</UserSecretsId>
  </PropertyGroup>

</Project>
